### ISSUE TITLE
predict a single image

### ISSUE THREAD

**Issue by ghost** [zzzxxxttt/simple_detectron2_EfficientDet#1]
@zzzxxxttt 
how to predict a single image

**Comment by zzzxxxttt** [comment]
You can use the demo/demo.py from detectron2, you may need to modify it to work with this repo.

**Comment by ghost** [comment]
- modify what values, the demo.py is very basic.
- do you mean `--config-file` and `--opts MODEL.WEIGHTS`
- have you tested your implementation?
